---
- name: 
  hosts: all 
  gather_facts: false
  tasks:
    - name: nginx web server
      docker_container:
        name: mydata
        image: nginx

    - name: ubuntu container start
      docker_container:
        name: mycontainer
        state: present
        image: ubuntu
        command: sleep infinity
