---
- name: Postfix Config
  hosts: all
  user: root
  tasks: 
    - name: postfix is installed and updated
      yum: 
        name: postfix
        state: latest
      notify: update_postfix
    - name: Postfix is installed and updated
      service:  
        name: postfix
        state: started        
    handlers: 
    - name: update_postfix
      service:
        name: postfix
        state: restarted
