---
- name: Ubuntu docker 
  hosts: all  
  tasks: 
    - name: Start Pulling Ubuntu 
      docker_image: 
        name: ubuntu:14.04
        source: pull 
    - name: Start a container with a command
      docker_container:
        name: sleepy
        image: ubuntu:14.04
        command: ["sleep", "infinity"]
    - name: Stop a container
      docker_container:
        name: sleepy
        state: absent

