---
- name: Example play using tagging
  hosts:
    - servera
    - serverb
  tasks:
  - name: Notify start of process
    debug:
      msg: Beginning httpd setup
  - block:
    - name: Ensure httpd packages are installed
      yum:
        name:
          - httpd
          - php
          - git
          - php-mysqlnd
        state: present
    - name: Template a file to /etc/files.conf
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      tags: 
        - template
    - name: Ensure SELinux allows httpd connections to a remote database
      seboolean:
        name: httpd_can_network_connect_db
        state: true
        persistent: true
    - name: Ensure httpd service is started and enabled
      service:
        name: httpd
        state: restarted
        enabled: true
      tags:
        - webserver 
    - name: Ensure required packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mod_ssl
        - httpd-tools   
        - mariadb-server
        - mariadb
        - php
        - php-mysqlnd
    - name: Ensure the services are enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: True
      loop:
        - httpd
        - mariadb
    - name: 
      firewalld: 
        service: httpd
        immediate: yes 
        permanent: yes 
        state: enabled
