---
- name: deployment of web  
  hosts: all
  tasks: 
    - name: Removing apache package
      yum: 
        name: 
          - httpd
          - mod_ssl
          - mariadb 
        state: absent
    - name: 
      firewalld: 
        service: http
        permanent: true
        immediate: yes 
        state: enabled
